USE board_db;

CREATE TABLE comments (
	id INT AUTO_INCREMENT PRIMARY KEY,
    postId INT NOT NULL,
    author VARCHAR(255) NOT NULL,
    content TEXT NOT NULL,
    createAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (postId) REFERENCES posts(id) ON DELETE CASCADE
);

-- 컬럼명 수정
ALTER TABLE comments CHANGE COLUMN postid postId INT NOT NULL;
   
ALTER TABLE comments CHANGE COLUMN createAt createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP;